### ISSUE TITLE
This might not be working anymore?

### ISSUE THREAD

**Issue by jedmund** [marcqualie/cloudapp-export#3]
I stumbled upon this, and upon trying to get it to work, Cloudapp returns a "Redirecting..." HTML page instead of JSON data, which obviously can't be parsed. I'm not familiar with how to debug Ruby gems, but running curl on their servers still works, and everything looks fine, so I'm quite confused.

Any help would be greatly appreciated!

**Comment by marcqualie** [comment]
Thanks for the feedback @jedmund! I have a version about to be realised (haven't had time lately) which is a pretty big rewrite and not yet pushed to rubygems. I'll let you know when it's available in the next few days.

Are you using the version from rubygems, or the source code directly?

**Comment by jedmund** [comment]
The rubygems version didn't seem to be properly installing the binary in my
path (in that `cloudapp-export` did nothing) so I downloaded the code and
was doing things that way.

Thanks for this tool! Trying to finally migrate data off Cloudapp so I can
stop paying for it but naturally they made it very difficult.

**Comment by marcqualie** [comment]
Hey @jedmund I've just pushed the refactored and working version to rubygems. You should now be able to install it using `gem install cloudapp-export`. Then you can use the following commands:

```
cloudapp-export all --username YOUREMAIL --limit 500
```

Note that it still needs a little work to be smoother, such as showing connection progress, but it works on my account with over 2500 items. It may look like it is just hanging but initially it's just downloading the very large .json file from cloudapp API.

Let me know if you run into anymore problems.

You can of course still use the codebase directly rather than rubygems to achive the same result.

**Comment by jedmund** [comment]
Thanks for the refactored version!

When putting in my password, it looks like maybe the IO isn't being converted properly to a string:

```
Password: ********************
Traceback (most recent call last):
	17: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	16: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	15: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/cloudapp-export:23:in `<main>'
	14: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/cloudapp-export:23:in `load'
	13: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/bin/cloudapp-export:10:in `<top (required)>'
	12: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	11: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	10: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 9: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 8: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/cli.rb:28:in `all'
	 7: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/exporter.rb:14:in `export_all'
	 6: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/item_list.rb:19:in `count'
	 5: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/item_list.rb:45:in `load'
	 4: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/api.rb:19:in `request'
	 3: from /Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/uri/generic.rb:505:in `password='
	 2: from /Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/uri/generic.rb:431:in `check_password'
	 1: from /Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/uri/generic.rb:431:in `!~'
/Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/uri/generic.rb:431:in `=~': no implicit conversion of IO into String (TypeError)
```

When putting my password in via CLI (just to test, I changed it beforehand), this error happens:

```
WARNING: Passing password via the command line is not recommended!
Traceback (most recent call last):
	15: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
	14: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	13: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/cloudapp-export:23:in `<main>'
	12: from /Users/justin/.rvm/gems/ruby-2.5.0/bin/cloudapp-export:23:in `load'
	11: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/bin/cloudapp-export:10:in `<top (required)>'
	10: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	 9: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	 8: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	 7: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	 6: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/cli.rb:28:in `all'
	 5: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/exporter.rb:14:in `export_all'
	 4: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/item_list.rb:19:in `count'
	 3: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/item_list.rb:46:in `load'
	 2: from /Users/justin/.rvm/gems/ruby-2.5.0/gems/cloudapp-export-0.2.1/lib/cloudapp_export/api.rb:61:in `data'
	 1: from /Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:156:in `parse'
/Users/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/json/common.rb:156:in `parse': 765: unexpected token at '<html><body>You are being <a href="https://cl.ly/502">redirected</a>.</body></html>' (JSON::ParserError)
```

I just installed via `gem install` so I'm assuming I do have the right version. I might try to pull from Github and try master instead.

**Comment by marcqualie** [comment]
Thanks for the detailed stack traces, very helpful. I will try to replicate the first issue with ruby 2.5, but the second appears to be with the URLs from your account. It wants to redurect rather than download the file. I'm also seeing this on some files on my account, which is possibly an encoding issue. Will update tomorrow.

**Comment by marcqualie** [comment]
@jedmund I've pushed a new version ([v0.2.2](https://github.com/marcqualie/cloudapp-export/compare/v0.2.1...v0.2.2)) which fixes the above issues that I could replicate on my account.

You will now get much better feedback when errors happen.

I wasn't able to replicate the second redirect issue, but I belive it was due to the URL encoding on the filename, which has now been patched.

`gem install cloudapp-export` will update to the latest version.
